# Generated by Django 2.2.16 on 2023-01-24 18:05

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20230124_2058'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='check-follow_self',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, user=django.db.models.expressions.F('author')), name='check_follow_self'),
        ),
    ]
